// <auto-generated />
namespace SessionsSepet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deletebizimkullanici2ü : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletebizimkullanici2ü));
        
        string IMigrationMetadata.Id
        {
            get { return "202104171101511_deletebizimkullanici2ü"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
